# Generated by Django 5.2.5 on 2025-08-20 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "icnumber",
                    models.CharField(
                        blank=True,
                        help_text="Enter ic number",
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notelefon",
                    models.CharField(
                        blank=True,
                        help_text="Enter phone number",
                        max_length=11,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
